<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class NfeItem extends Model
{
    use HasFactory;
    protected  $fillable= [
        'nfe_id',
        'numero_item',
        'produto_id',
        'livre',
        'cProd',
        'sku',
        'cEAN',
        'xProd',
        'NCM',
        'importado',
        'cBenef',
        'NVE',
        'EXTIPI',
        'CFOP',
        'uCom',
        'qCom',
        'vUnCom',
        'vProd',
        'cEANTrib',
        'proporcao',
        'uTrib',
        'qTrib',
        'vUnTrib',
        'vFrete',
        'vSeg',
        'desconto_item',
        'desconto_rateio',
        'vDesc',
        'vOutro',
        'indTot',
        'xPed',
        'nItemPed',
        'nFCI',
        'cstIPI',
        'clEnq',
        'CNPJProd',
        'cSelo',
        'qSelo',
        'cEnq',
        'vIPI',
        'vBCIPI',
        'vICMSTRet',
        'pIPI',
        'qUnidIPI',
        'vUnidIPI',
        'tipo_calc_ipi',
        'cstCOFINS',
        'vBCCOFINSST',
        'qBCProdConfisST',
        'qBCProdPisST',
        'vBCPISST',        
        'pCOFINS',
        'tipo_calc_cofins',
        'vAliqProd_cofins',
        'vBCCOFINS',
        'vCOFINS',
        'vCOFINSST',
        'tipo_calc_cofinsst',
        'pCOFINSST',
        'vAliqProd_cofinsst',
        'cstPIS',
        'tipo_calc_pis',
        'vBCPIS',
        'pPIS',
        'vPIS',
        'vAliqProd_pis',
        'tipo_calc_pisst',
        'pPISST',
        'vAliqProd_pisst',
        'orig',
        'cstICMS',
        'modBC',
        'vBCICMS',
        'pICMS',
        'vICMS',
        'pFCP',
        'vFCP',
        'vBCFCP',
        'pMVAST',
        'pRedBCST',
        'vBCST',
        'pICMSST',
        'vICMSST',
        'vBCFCPST',
        'pFCPST',
        'vFCPST',
        'vICMSDeson',
        'motDesICMS',
        'pRedBC',
        'vICMSOp',
        'pDif',
        'vICMSDif',
        'vBCSTRet',
        'pST',
        'vICMSSTRet',
        'vBCFCPSTRet',
        'pFCPSTRet',
        'vFCPSTRet',
        'pRedBCEfet',
        'vBCEfet',
        'pICMSEfet',
        'vICMSEfet',
        'vICMSSubstituto',
        'modBCST',
        'pBCOp',
        'UFST',
        'vBCSTDest',
        'vICMSSTDest',
        'CSOSN',
        'pCredSN',
        'vCredICMSSN',
        'vBCUFDest',
        'vBCFCPUFDest',
        'pFCPUFDest',
        'pICMSUFDest',
        'pICMSInter',
        'pICMSInterPart',
        'vFCPUFDest',
        'vICMSUFDest',
        'vICMSUFRemet',
        'destaca_icms',
        'estadual','municipal','nacionalfederal','importadosfederal',
        'vbc_somente_produto','vbc_frete','vbc_ipi','vbc_outros', 'vbc_seguro','vbc_desconto',
        'ipi_somente_produto','ipi_frete','ipi_outros','ipi_seguro','ipi_desconto',
        'pis_somente_produto','pis_frete','pis_ipi','pis_outros','pis_seguro','pis_desconto',
        'cofins_somente_produto','cofins_frete','cofins_ipi','cofins_outros','cofins_seguro','cofins_desconto',
        'cst900_icms','cst900_redbc','cst900_credisn','cst900_st','cst900_redbcst',
        'subtotal_liquido','desconto_percentual','desconto_por_valor','desconto_por_unidade','total_desconto_item','preco_original'
        
    ];
    
    public function produto(){
        return $this->belongsTo(Produto::class, 'produto_id');
    }
}

