<?php

namespace Database\Seeders;

use App\Models\Banco;
use Illuminate\Database\Seeder;

class BancoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Banco::Create(['codigo' =>'999', 'banco' => 'Caixa Interno']);
        Banco::Create(['codigo' =>'001', 'banco' => 'Banco do Brasil S.A.']);
        Banco::Create(['codigo' =>'004', 'banco' => 'Banco do Nordeste do Brasil S.A.']);
        Banco::Create(['codigo' =>'033', 'banco' => 'Banco Santander (Brasil) S.A.']);
        Banco::Create(['codigo' =>'104', 'banco' => 'Caixa Econômica Federal']);
        Banco::Create(['codigo' =>'341', 'banco' => 'Itaú Unibanco S.A.']);
        Banco::Create(['codigo' =>'260', 'banco' => 'Nu Pagamentos S.A (Nubank)']);
        Banco::Create(['codigo' =>'290', 'banco' => 'Pagseguro Internet S.A']);
        Banco::Create(['codigo' =>'237', 'banco' => 'Banco Bradesco S.A.']);
        Banco::Create(['codigo' =>'246', 'banco' => 'Banco ABC Brasil S.A.']);
        Banco::Create(['codigo' =>'748', 'banco' => 'Banco Cooperativo Sicredi S.A.']);
        Banco::Create(['codigo' =>'117', 'banco' => 'Advanced Cc Ltda']);
        Banco::Create(['codigo' =>'121', 'banco' => 'Banco Agibank S.A.']);
        Banco::Create(['codigo' =>'172', 'banco' => 'Albatross Ccv S.A']);
        Banco::Create(['codigo' =>'188', 'banco' => 'Ativa Investimentos S.A']);
        Banco::Create(['codigo' =>'654', 'banco' => 'Banco A.J.Renner S.A.']);
        Banco::Create(['codigo' =>'246', 'banco' => 'Banco ABC Brasil S.A.']);
        Banco::Create(['codigo' =>'075', 'banco' => 'Banco ABN AMRO S.A']);
        Banco::Create(['codigo' =>'121', 'banco' => 'Banco Agibank S.A.']);
        Banco::Create(['codigo' =>'025', 'banco' => 'Banco Alfa S.A.']);
        Banco::Create(['codigo' =>'641', 'banco' => 'Banco Alvorada S.A.']);
        Banco::Create(['codigo' =>'065', 'banco' => 'Banco Andbank (Brasil) S.A.']);
        Banco::Create(['codigo' =>'213', 'banco' => 'Banco Arbi S.A.']);
        Banco::Create(['codigo' =>'096', 'banco' => 'Banco B3 S.A.']);
        Banco::Create(['codigo' =>'024', 'banco' => 'Banco BANDEPE S.A.']);
        Banco::Create(['codigo' =>'318', 'banco' => 'Banco BMG S.A.']);
        Banco::Create(['codigo' =>'752', 'banco' => 'Banco BNP Paribas Brasil S.A.']);
        Banco::Create(['codigo' =>'107', 'banco' => 'Banco BOCOM BBM S.A.']);
        Banco::Create(['codigo' =>'063', 'banco' => 'Banco Bradescard S.A.']);
        Banco::Create(['codigo' =>'036', 'banco' => 'Banco Bradesco BBI S.A.']);
        Banco::Create(['codigo' =>'122', 'banco' => 'Banco Bradesco BERJ S.A.']);
        Banco::Create(['codigo' =>'204', 'banco' => 'Banco Bradesco Cartões S.A.']);
        Banco::Create(['codigo' =>'394', 'banco' => 'Banco Bradesco Financiamentos S.A.']);
        Banco::Create(['codigo' =>'218', 'banco' => 'Banco BS2 S.A.']);
        Banco::Create(['codigo' =>'208', 'banco' => 'Banco BTG Pactual S.A.']);
        Banco::Create(['codigo' =>'336', 'banco' => 'Banco C6 S.A – C6 Bank']);
        Banco::Create(['codigo' =>'473', 'banco' => 'Banco Caixa Geral – Brasil S.A.']);
        Banco::Create(['codigo' =>'412', 'banco' => 'Banco Capital S.A.']);
        Banco::Create(['codigo' =>'040', 'banco' => 'Banco Cargill S.A.']);
        Banco::Create(['codigo' =>'368', 'banco' => 'Banco Carrefour']);
        Banco::Create(['codigo' =>'266', 'banco' => 'Banco Cédula S.A.']);
        Banco::Create(['codigo' =>'739', 'banco' => 'Banco Cetelem S.A.']);
        Banco::Create(['codigo' =>'233', 'banco' => 'Banco Cifra S.A.']);
        Banco::Create(['codigo' =>'745', 'banco' => 'Banco Citibank S.A.']);
        Banco::Create(['codigo' =>'241', 'banco' => 'Banco Clássico S.A.']);
        Banco::Create(['codigo' =>'756', 'banco' => 'Banco Cooperativo do Brasil S.A. ']);
        Banco::Create(['codigo' =>'748', 'banco' => 'Banco Cooperativo Sicredi S.A.']);
        Banco::Create(['codigo' =>'222', 'banco' => 'Banco Credit Agricole Brasil S.A.']);
        Banco::Create(['codigo' =>'505', 'banco' => 'Banco Credit Suisse (Brasil) S.A.']);
        Banco::Create(['codigo' =>'069', 'banco' => 'Banco Crefisa S.A.']);
        Banco::Create(['codigo' =>'003', 'banco' => 'Banco da Amazônia S.A.']);
        Banco::Create(['codigo' =>'083', 'banco' => 'Banco da China Brasil S.A.']);
        Banco::Create(['codigo' =>'707', 'banco' => 'Banco Daycoval S.A.']);
        Banco::Create(['codigo' =>'051', 'banco' => 'Banco de Desenvolvimento do Espírito Santo S.A.']);
        Banco::Create(['codigo' =>'300', 'banco' => 'Banco de La Nacion Argentina']);
        Banco::Create(['codigo' =>'495', 'banco' => 'Banco de La Provincia de Buenos Aires']);
        Banco::Create(['codigo' =>'335', 'banco' => 'Banco Digio S.A']);
        Banco::Create(['codigo' =>'047', 'banco' => 'Banco do Estado de Sergipe S.A.']);
        Banco::Create(['codigo' =>'037', 'banco' => 'Banco do Estado do Pará S.A.']);
        Banco::Create(['codigo' =>'041', 'banco' => 'Banco do Estado do Rio Grande do Sul S.A.']);
        Banco::Create(['codigo' =>'196', 'banco' => 'Banco Fair Corretora de Câmbio S.A']);
        Banco::Create(['codigo' =>'265', 'banco' => 'Banco Fator S.A.']);
        Banco::Create(['codigo' =>'224', 'banco' => 'Banco Fibra S.A.']);
        Banco::Create(['codigo' =>'626', 'banco' => 'Banco Ficsa S.A.']);
        Banco::Create(['codigo' =>'094', 'banco' => 'Banco Finaxis S.A.']);
        Banco::Create(['codigo' =>'612', 'banco' => 'Banco Guanabara S.A.']);
        Banco::Create(['codigo' =>'012', 'banco' => 'Banco Inbursa S.A.']);
        Banco::Create(['codigo' =>'604', 'banco' => 'Banco Industrial do Brasil S.A.']);
        Banco::Create(['codigo' =>'653', 'banco' => 'Banco Indusval S.A.']);
        Banco::Create(['codigo' =>'077', 'banco' => 'Banco Inter S.A.']);
        Banco::Create(['codigo' =>'249', 'banco' => 'Banco Investcred Unibanco S.A.']);
        Banco::Create(['codigo' =>'184', 'banco' => 'Banco Itaú BBA S.A.']);
        Banco::Create(['codigo' =>'029', 'banco' => 'Banco Itaú Consignado S.A.']);
        Banco::Create(['codigo' =>'479', 'banco' => 'Banco ItauBank S.A']);
        Banco::Create(['codigo' =>'376', 'banco' => 'Banco J. P. Morgan S.A.']);
        Banco::Create(['codigo' =>'074', 'banco' => 'Banco J. Safra S.A.']);
        Banco::Create(['codigo' =>'217', 'banco' => 'Banco John Deere S.A.']);
        Banco::Create(['codigo' =>'076', 'banco' => 'Banco KDB S.A.www.bancokdb.com.br']);
        Banco::Create(['codigo' =>'757', 'banco' => 'Banco KEB HANA do Brasil S.A.']);
        Banco::Create(['codigo' =>'600', 'banco' => 'Banco Luso Brasileiro S.A.']);
        Banco::Create(['codigo' =>'243', 'banco' => 'Banco Máxima S.A.']);
        Banco::Create(['codigo' =>'720', 'banco' => 'Banco Maxinvest S.A.']);
        Banco::Create(['codigo' =>'389', 'banco' => 'Banco Mercantil de Investimentos S.A.']);
        Banco::Create(['codigo' =>'389', 'banco' => 'Banco Mercantil do Brasil S.A.']);
        Banco::Create(['codigo' =>'370', 'banco' => 'Banco Mizuho do Brasil S.A.']);
        Banco::Create(['codigo' =>'746', 'banco' => 'Banco Modal S.A.']);
        Banco::Create(['codigo' =>'066', 'banco' => 'Banco Morgan Stanley S.A.']);
        Banco::Create(['codigo' =>'456', 'banco' => 'Banco MUFG Brasil S.A.www.br.bk.mufg.jp']);
        Banco::Create(['codigo' =>'007', 'banco' => 'Banco Nacional de Desenvolvimento Econômico e Social – BNDES']);
        Banco::Create(['codigo' =>'169', 'banco' => 'Banco Olé Bonsucesso Consignado S.A.']);
        Banco::Create(['codigo' =>'111', 'banco' => 'Banco Oliveira Trust Dtvm S.A']);
        Banco::Create(['codigo' =>'079', 'banco' => 'Banco Original do Agronegócio S.A.']);
        Banco::Create(['codigo' =>'212', 'banco' => 'Banco Original S.A.']);
        Banco::Create(['codigo' =>'712', 'banco' => 'Banco Ourinvest S.A.']);
        Banco::Create(['codigo' =>'623', 'banco' => 'Banco PAN S.A.']);
        Banco::Create(['codigo' =>'611', 'banco' => 'Banco Paulista S.A.']);
        Banco::Create(['codigo' =>'643', 'banco' => 'Banco Pine S.A.']);
        Banco::Create(['codigo' =>'658', 'banco' => 'Banco Porto Real de Investimentos S.A.']);
        Banco::Create(['codigo' =>'747', 'banco' => 'Banco Rabobank International Brasil S.A.']);
        Banco::Create(['codigo' =>'633', 'banco' => 'Banco Rendimento S.A.']);
        Banco::Create(['codigo' =>'741', 'banco' => 'Banco Ribeirão Preto S.A.']);
        Banco::Create(['codigo' =>'120', 'banco' => 'Banco Rodobens S.A.']);
        Banco::Create(['codigo' =>'422', 'banco' => 'Banco Safra S.A.']);
        Banco::Create(['codigo' =>'630', 'banco' => 'Banco Smartbank S.A.']);
        Banco::Create(['codigo' =>'637', 'banco' => 'Banco Sofisa S.A.www.sofisa.com.br']);
        Banco::Create(['codigo' =>'655', 'banco' => 'Banco Votorantim S.A.']);
        Banco::Create(['codigo' =>'610', 'banco' => 'Banco VR S.A.']);
        Banco::Create(['codigo' =>'119', 'banco' => 'Banco Western Union do Brasil S.A.']);
        Banco::Create(['codigo' =>'124', 'banco' => 'Banco Woori Bank do Brasil S.A.']);
        Banco::Create(['codigo' =>'348', 'banco' => 'Banco Xp S/A']);
        Banco::Create(['codigo' =>'081', 'banco' => 'BancoSeguro S.A.']);
        Banco::Create(['codigo' =>'021', 'banco' => 'BANESTES S.A. Banco do Estado do Espírito Santo']);
        Banco::Create(['codigo' =>'755', 'banco' => 'Bank of America Merrill Lynch Banco Múltiplo S.A.']);
        Banco::Create(['codigo' =>'268', 'banco' => 'Barigui Companhia Hipotecária']);
        Banco::Create(['codigo' =>'250', 'banco' => 'BCV – Banco de Crédito e Varejo S.A.']);
        Banco::Create(['codigo' =>'144', 'banco' => 'BEXS Banco de Câmbio S.A.']);
        Banco::Create(['codigo' =>'253', 'banco' => 'Bexs Corretora de Câmbio S/A']);
        Banco::Create(['codigo' =>'134', 'banco' => 'Bgc Liquidez Dtvm Ltda']);
        Banco::Create(['codigo' =>'017', 'banco' => 'BNY Mellon Banco S.A.']);
        Banco::Create(['codigo' =>'301', 'banco' => 'Bpp Instituição De Pagamentos S.A']);
        Banco::Create(['codigo' =>'126', 'banco' => 'BR Partners Banco de Investimento S.A.']);
        Banco::Create(['codigo' =>'070', 'banco' => 'BRB – Banco de Brasília S.A.']);
        Banco::Create(['codigo' =>'092', 'banco' => 'Brickell S.A. Crédito, Financiamento e Investimentow']);
        Banco::Create(['codigo' =>'173', 'banco' => 'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.']);
        Banco::Create(['codigo' =>'142', 'banco' => 'Broker Brasil Cc Ltda']);
        Banco::Create(['codigo' =>'292', 'banco' => 'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.']);
        Banco::Create(['codigo' =>'011', 'banco' => 'C.Suisse Hedging-Griffo Cv S.A (Credit Suisse)']);
        Banco::Create(['codigo' =>'288', 'banco' => 'Carol Distribuidora de Títulos e Valor Mobiliários Ltda']);
        Banco::Create(['codigo' =>'130', 'banco' => 'Caruana Scfi']);
        Banco::Create(['codigo' =>'159', 'banco' => 'Casa Credito S.A']);
        Banco::Create(['codigo' =>'016', 'banco' => 'Ccm Desp Trâns Sc E Rs']);
        Banco::Create(['codigo' =>'089', 'banco' => 'Ccr Reg Mogiana']);
        Banco::Create(['codigo' =>'114', 'banco' => 'Central Cooperativa De Crédito No Estado Do Espírito Santo']);
        Banco::Create(['codigo' =>'320', 'banco' => 'China Construction Bank (Brasil) Banco Múltiplo S.A.']);
        Banco::Create(['codigo' =>'477', 'banco' => 'Citibank N.A.']);
        Banco::Create(['codigo' =>'180', 'banco' => 'Cm Capital Markets Cctvm Ltda']);
        Banco::Create(['codigo' =>'127', 'banco' => 'Codepe Cvc S.A']);
        Banco::Create(['codigo' =>'163', 'banco' => 'Commerzbank Brasil S.A. – Banco Múltiplo']);
        Banco::Create(['codigo' =>'060', 'banco' => 'Confidence Cc S.A']);
        Banco::Create(['codigo' =>'098', 'banco' => 'Credialiança Ccr']);
        Banco::Create(['codigo' =>'010', 'banco' => 'Credicoamo']);
        Banco::Create(['codigo' =>'133', 'banco' => 'Cresol Confederação']);
        Banco::Create(['codigo' =>'182', 'banco' => 'Dacasa Financeira S/A']);
        Banco::Create(['codigo' =>'707', 'banco' => 'Banco Daycoval S.A.']);
        Banco::Create(['codigo' =>'487', 'banco' => 'Deutsche Bank S.A. – Banco Alemão']);
        Banco::Create(['codigo' =>'140', 'banco' => 'Easynvest – Título Cv S.A']);
        Banco::Create(['codigo' =>'149', 'banco' => 'Facta S.A. Cfi']);
        Banco::Create(['codigo' =>'285', 'banco' => 'Frente Corretora de Câmbio Ltda.']);
        Banco::Create(['codigo' =>'278', 'banco' => 'Genial Investimentos Corretora de Valores Mobiliários S.A.']);
        Banco::Create(['codigo' =>'138', 'banco' => 'Get Money Cc Ltda']);
        Banco::Create(['codigo' =>'064', 'banco' => 'Goldman Sachs do Brasil Banco Múltiplo S.A.']);
        Banco::Create(['codigo' =>'177', 'banco' => 'Guide Investimentos S.A. Corretora de Valores']);
        Banco::Create(['codigo' =>'146', 'banco' => 'Guitta Corretora de Câmbio Ltda']);
        Banco::Create(['codigo' =>'078', 'banco' => 'Haitong Banco de Investimento do Brasil S.A.']);
        Banco::Create(['codigo' =>'062', 'banco' => 'Hipercard Banco Múltiplo S.A.www.hipercard.com.br']);
        Banco::Create(['codigo' =>'189', 'banco' => 'HS Financeira S/A Crédito, Financiamento e Investimentos']);
        Banco::Create(['codigo' =>'269', 'banco' => 'HSBC Brasil S.A. – Banco de Investimento']);
        Banco::Create(['codigo' =>'271', 'banco' => 'IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.']);
        Banco::Create(['codigo' =>'157', 'banco' => 'Icap Do Brasil Ctvm Ltda']);
        Banco::Create(['codigo' =>'132', 'banco' => 'ICBC do Brasil Banco Múltiplo S.A.']);
        Banco::Create(['codigo' =>'492', 'banco' => 'ING Bank N.V.www.ing.com']);
        Banco::Create(['codigo' =>'139', 'banco' => 'Intesa Sanpaolo Brasil S.A. ']);
        Banco::Create(['codigo' =>'652', 'banco' => 'Itaú Unibanco Holding S.A.']);
        Banco::Create(['codigo' =>'488', 'banco' => 'JPMorgan Chase Bank, National Association']);
        Banco::Create(['codigo' =>'399', 'banco' => 'Kirton Bank S.A. – Banco Múltiplo']);
        Banco::Create(['codigo' =>'293', 'banco' => 'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.']);
        Banco::Create(['codigo' =>'105', 'banco' => 'Lecca Crédito, Financiamento e Investimento S/A']);
        Banco::Create(['codigo' =>'145', 'banco' => 'Levycam Ccv Ltda']);
        Banco::Create(['codigo' =>'113', 'banco' => 'Magliano S.A']);
        Banco::Create(['codigo' =>'323', 'banco' => 'Mercado Pago – Conta Do Mercado Livre']);
        Banco::Create(['codigo' =>'128', 'banco' => 'MS Bank S.A. Banco de Câmbio']);
        Banco::Create(['codigo' =>'137', 'banco' => 'Multimoney Cc Ltda']);
        Banco::Create(['codigo' =>'014', 'banco' => 'Natixis Brasil S.A. Banco Múltiplo']);
        Banco::Create(['codigo' =>'191', 'banco' => 'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.']);
        Banco::Create(['codigo' =>'753', 'banco' => 'Novo Banco Continental S.A.']);
        Banco::Create(['codigo' =>'613', 'banco' => 'Omni Banco S.A.www.bancopecunia.com.br']);
        Banco::Create(['codigo' =>'613', 'banco' => 'Omni Banco S.A.www.omni.com.br']);
        Banco::Create(['codigo' =>'254', 'banco' => 'Paraná Banco S.A.']);
        Banco::Create(['codigo' =>'326', 'banco' => 'Parati – Crédito Financiamento e Investimento S.A.']);
        Banco::Create(['codigo' =>'174', 'banco' => 'Pernambucanas Financ S.A']);
        Banco::Create(['codigo' =>'100', 'banco' => 'Planner Corretora De Valores S.A']);
        Banco::Create(['codigo' =>'125', 'banco' => 'Plural S.A. – Banco Múltiplo']);
        Banco::Create(['codigo' =>'093', 'banco' => 'Pólocred Scmepp Ltda']);
        Banco::Create(['codigo' =>'108', 'banco' => 'Portocred S.A']);
        Banco::Create(['codigo' =>'283', 'banco' => 'Rb Capital Investimentos Dtvm Ltda']);
        Banco::Create(['codigo' =>'101', 'banco' => 'Renascenca Dtvm Ltda']);
        Banco::Create(['codigo' =>'270', 'banco' => 'Sagitur Corretora de Câmbio Ltda.']);
        Banco::Create(['codigo' =>'751', 'banco' => 'Scotiabank Brasil S.A. Banco Múltiplo']);
        Banco::Create(['codigo' =>'276', 'banco' => 'Senff S.A. – Crédito, Financiamento e Investimento']);
        Banco::Create(['codigo' =>'545', 'banco' => 'Senso Ccvm S.A']);
        Banco::Create(['codigo' =>'190', 'banco' => 'Servicoop']);
        Banco::Create(['codigo' =>'183', 'banco' => 'Socred S.A']);
        Banco::Create(['codigo' =>'299', 'banco' => 'Sorocred Crédito, Financiamento e Investimento S.A.']);
        Banco::Create(['codigo' =>'118', 'banco' => 'Standard Chartered Bank (Brasil) ']);
        Banco::Create(['codigo' =>'197', 'banco' => 'Stone Pagamentos S.A']);
        Banco::Create(['codigo' =>'095', 'banco' => 'Travelex Banco de Câmbio S.A.']);
        Banco::Create(['codigo' =>'143', 'banco' => 'Treviso Corretora de Câmbio S.A.']);
        Banco::Create(['codigo' =>'131', 'banco' => 'Tullett Prebon Brasil Cvc Ltda']);
        Banco::Create(['codigo' =>'129', 'banco' => 'UBS Brasil Banco de Investimento S.A.']);
        Banco::Create(['codigo' =>'91', 'banco' => 'Unicred Central Rs']);
        Banco::Create(['codigo' =>'136', 'banco' => 'Unicred Cooperativa']);
        Banco::Create(['codigo' =>'298', 'banco' => 'Vips Cc Ltda']);
        Banco::Create(['codigo' =>'102', 'banco' => 'Xp Investimentos S.A']);
        
    }
}
