<?php

namespace Database\Seeders;

use App\Models\ClassificacaoFinanceiraModel;
use Illuminate\Database\Seeder;

class ClassificacaoFinanceiraModeloSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.  .', 'descricao' => 'RECEITAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.  .', 'descricao' => 'DESPESAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.', 'descricao' => 'VENDAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.001', 'descricao' => 'COMISSAO RECEBIDA COM VENDAS DE EQUIP.', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.002', 'descricao' => 'RECEBIMENTOS VENDAS DE SOFTWARE PROPRIO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.003', 'descricao' => 'RECEBIMENTO ANTERIOR', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.004', 'descricao' => 'RECEBIMENTO CHEQUES DEVOLVIDOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.', 'descricao' => 'SALARIOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.001', 'descricao' => 'SALARIOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.002', 'descricao' => '13º SALARIO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.003', 'descricao' => 'FERIAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.004', 'descricao' => 'INSS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.005', 'descricao' => 'FGTS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.006', 'descricao' => 'RESCISAO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.007', 'descricao' => 'VALE TRANSPORTES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.008', 'descricao' => 'COMISSOES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.', 'descricao' => 'CUSTOS VARIAVEIS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.001', 'descricao' => 'COMPRAS/FORNECEDOR', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.002', 'descricao' => 'CHEQUES DEVOLVIDOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.003', 'descricao' => 'TROCAS DEFEITO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.004', 'descricao' => 'SIMPLES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.005', 'descricao' => 'IMP.RENDA JURIDICA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.006', 'descricao' => 'IMP.RENDA ALUGUEL', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.007', 'descricao' => 'PIS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.008', 'descricao' => 'COFINS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.009', 'descricao' => 'FINSOCIAL', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.010', 'descricao' => 'ICMS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.', 'descricao' => 'CUSTOS OPERACIONAIS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.001', 'descricao' => 'RETIRADA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.002', 'descricao' => 'ALUGUEL', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.003', 'descricao' => 'AGUA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.004', 'descricao' => 'LUZ', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.005', 'descricao' => 'TELEFONE', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.006', 'descricao' => 'CONTABILIDADE', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.007', 'descricao' => 'MATERIAL INFORMATICA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.008', 'descricao' => 'MATERIAL ESCRITORIO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.009', 'descricao' => 'MATERIAL LIMPEZA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.010', 'descricao' => 'MANUTENCAO PROGRAMAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.011', 'descricao' => 'MANUTENCAO MICROS/IMPRESSORAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.012', 'descricao' => 'CAIXAS EMBALAGEM', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.013', 'descricao' => 'SACOLAS EMBALAGENS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.014', 'descricao' => 'FITAS EMBALAGENS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.015', 'descricao' => 'IPTU', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.016', 'descricao' => 'ESTACIONAMENTO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.017', 'descricao' => 'VEICULOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.018', 'descricao' => 'GASOLINA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.019', 'descricao' => 'FRETES E CARRETOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.020', 'descricao' => 'TAXI', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.021', 'descricao' => 'SEDEX/CORREIO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.022', 'descricao' => 'CARTORIO, COPIAS, AUTENTICACOES ETC', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.023', 'descricao' => 'ASSINATURA JORNAIS/REVISTAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.024', 'descricao' => 'SEGUROS VEICULOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.025', 'descricao' => 'SEGURO LOJA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.04.', 'descricao' => 'INVESTIMENTOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.04.001', 'descricao' => 'VEICULOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.04.002', 'descricao' => 'MICROS/IMPRESSORAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.04.003', 'descricao' => 'REFORMAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.026', 'descricao' => 'CONDOMINIO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.027', 'descricao' => 'DESPESAS COM INTERNET', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.05.', 'descricao' => 'SERVICOS DE TERCEIROS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.05.001', 'descricao' => 'MANUTENCAO PREDIAL', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.06.', 'descricao' => 'MOVEIS E UTENSILIOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.06.001', 'descricao' => 'CADEIRAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.02.', 'descricao' => 'OUTRAS ENTRADAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.02.001', 'descricao' => 'ENTRADAS DE INVESTIMENTOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.006', 'descricao' => 'RECEBIMENTOS DE MANUTENCAO DE SISTEMAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.03.', 'descricao' => 'SERVIÃ‡OS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.03.001', 'descricao' => 'SERVIÃ‡OS MANUTENCAO DE MAQUINAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.03.002', 'descricao' => 'SERVIÃ‡OS MANUTENÃ‡ÃƒO EM SOFTWARE PROP', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.03.003', 'descricao' => 'CONSULTORIA PRESTADAS EM SOFTWARE TERCE', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.03.004', 'descricao' => 'DESENVOLVIMENTO DE SISTEMAS ESPECIFICOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.03.005', 'descricao' => 'CUSTOMIZACOES EM SISTEMAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.06.002', 'descricao' => 'MOVEIS E UTENSILIOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.028', 'descricao' => 'PEDAGIOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.07.', 'descricao' => 'DESPESAS DIVERSAS COM CLIENTES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.07.001', 'descricao' => 'DESPESAS COM EQUIPAMENTOS DE CLIENTES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.012', 'descricao' => 'REEMBOLSOS POR PAGAMENTO INDEVIDO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.08.', 'descricao' => 'MARKETING', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.08.001', 'descricao' => 'DESIGN LOGOMARCA, CARTOES E UNIFORME', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.09.', 'descricao' => 'TAXAS E IMPOSTOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.09.001', 'descricao' => 'CONTRIBUICAO SINDICAL PATRONAL', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.03.006', 'descricao' => 'HOSPEDAGEM SITE', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.008', 'descricao' => 'DESENVOLVIMENTO WEBSITE', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.09.002', 'descricao' => 'TFE - TAXA FISCALIZACAO ESTABELECIMENTO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.07.002', 'descricao' => 'CARTOES DE VISITA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.07.003', 'descricao' => 'TRANSPORTES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.07.004', 'descricao' => 'CORREIOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.029', 'descricao' => 'CONFECCAO NOTAS FISCAIS DE SAIDA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.09.003', 'descricao' => 'CPMF', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.09.004', 'descricao' => 'TARIFAS BANCARIAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.011', 'descricao' => 'KILOMETRAGEM', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.02.002', 'descricao' => 'ENTRADA REFORÃ‡O CAIXA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.009', 'descricao' => 'VENDAS MAQUINAS, EQUIPAM.E ACESSORIOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.10.', 'descricao' => 'MARKETING', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.10.001', 'descricao' => 'ANUNCIO JORNAIS/REVISTAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'03.  .', 'descricao' => 'INVESTIMENTO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'03.01.', 'descricao' => 'APLICAÃ‡ÃƒO FINANCEIRA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'03.01.001', 'descricao' => 'RENDIMENTOS APLICACAO FINANCEIRA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'03.01.002', 'descricao' => 'TAXAS APLICACAO FINANCEIRA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'03.01.003', 'descricao' => 'DI', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.11.', 'descricao' => 'MATERIAL USO/CONSUMO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.11.001', 'descricao' => 'MATERIAL USO/CONSUMO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.12.', 'descricao' => 'ALIMENTAÇÃO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.12.001', 'descricao' => 'LANCHES E REFEICOES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.010', 'descricao' => 'ATIVO IMOBILIZADO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.030', 'descricao' => 'SUPRIMENTOS INFORMATICA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.02.003', 'descricao' => 'BONUS CPFM PREMIO - APLICACAO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'03.02.', 'descricao' => 'PATRIMONIO MATERIAL', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'03.02.001', 'descricao' => 'AQUISICOES DE ATIVO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.009', 'descricao' => 'TAXA ACOMPANHAMENTO ESTAGIARIO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.09.005', 'descricao' => 'I.R.R.F.', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.09.006', 'descricao' => 'ISS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.013', 'descricao' => 'COMPRAS PARA CLIENTES COM REEMBOLSO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.05.002', 'descricao' => 'PAGAMENTO SERVICOS DE TERCEIROS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.07.005', 'descricao' => 'DEVOLUÃ‡AO POR PAGAMENTO INDEVIDO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.09.007', 'descricao' => 'IRPJ', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.09.008', 'descricao' => 'CSLL', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.011', 'descricao' => 'GRATIFICAÃ‡ÃƒO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.010', 'descricao' => 'BOLSA AUXILIO - ESTAGIO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.011', 'descricao' => 'CONTRIBUICAO SINDICAL - FUNCIONARIOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.05.003', 'descricao' => 'LOCACAO LICENCA SOFTWARE-TERCEIROS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.09.009', 'descricao' => 'IOF', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.012', 'descricao' => 'TREINAMENTOS PARA CLIENTES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.13.', 'descricao' => 'COMISSOES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.13.001', 'descricao' => 'COMISSAO VENDA DE SOFTWARE', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.13.002', 'descricao' => 'COMISSAO VENDA EQUIPAMENTOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.13.003', 'descricao' => 'COMISSÃO SERVIÇOS DE TI - MAQUINAS/RE', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.04.', 'descricao' => 'EMPRESTIMOS CONCEDIDOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.04.001', 'descricao' => 'EMPRESTIMOS A FUNCIONARIOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.07.006', 'descricao' => 'DESPESAS COM VISITAS A CLIENTES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.  .', 'descricao' => 'DESPESAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.  .', 'descricao' => 'RECEITAS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.', 'descricao' => 'EDUCAÃ‡ÃƒO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.001', 'descricao' => 'FACULDADE', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.002', 'descricao' => 'ESCOLA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.014', 'descricao' => 'PCMSO - RPA - SEGURANCA TRABALHO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.05.004', 'descricao' => 'FAXINA - DIARISTA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.015', 'descricao' => 'CESTAS NATAL', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.016', 'descricao' => 'SERASA - CERTIFICADO DIGITAL', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.02.017', 'descricao' => 'ADIANTAMENTO REEMBOLSO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'03.02.002', 'descricao' => 'DESPESAS COM CARTAO DE CREDITO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.012', 'descricao' => 'AJUDA DE CUSTO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.03.031', 'descricao' => 'CERTIFICADO DIGITAL', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.14.', 'descricao' => 'DESPESA DE CONVENIO - FUNCIONARIOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.14.001', 'descricao' => 'DESPESA COM FUNCIONARIOS - CONVENIO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.08.002', 'descricao' => 'PATROCINIO FUTEBOL', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.15.', 'descricao' => 'RECISÃO TRABALHISTA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.15.001', 'descricao' => 'FGTS RECISAO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.16.', 'descricao' => 'CONSORCIO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.16.001', 'descricao' => 'CONSORCIO VEICULOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.17.', 'descricao' => 'UNIFORMES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.17.001', 'descricao' => 'UNIFORMES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'D']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.18.', 'descricao' => 'DESPESAS COM VEICULO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.18.001', 'descricao' => 'INSPEÃ‡ÃƒO VEICULAR', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.19.', 'descricao' => 'NOTA DE DEBITO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.19.001', 'descricao' => 'PAGAMENTO DE TITULOS DE CLIENTES', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.19.002', 'descricao' => 'RECEBIMENTO DE NOTA DE DEBITO(ND)', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'R']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.013', 'descricao' => 'MICROSOFT - SISTEMA OPERCIONAL', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'R']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.014', 'descricao' => 'VENDAS DE SUPRIMENTOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'R']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.03.007', 'descricao' => 'OUTROS SERVICOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.05.005', 'descricao' => 'PLANO ODONTOLOGICO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.04.004', 'descricao' => 'PREVIDENCIA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.20.', 'descricao' => 'CURSOS E TREINAMENTOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.20.001', 'descricao' => 'CURSOS DE PROGRAMACAO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'R']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.015', 'descricao' => 'LICENÃ‡A DE ANTIVIRUS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'R']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.03.008', 'descricao' => 'LICENÃ‡A ANTIVIRUS KASPERSKY', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'R']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.19.003', 'descricao' => 'NOTA DEBITO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'D']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.01.013', 'descricao' => 'SEGURO ESTAGIO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'D']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.18.002', 'descricao' => 'IPVA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'D']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.21.', 'descricao' => 'EMPRESTIMO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'D']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.21.001', 'descricao' => 'CAPITAL DE GIRO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'R']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.03.009', 'descricao' => 'RECEBIMENTO APLICATIVOS DELIVERY', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.016', 'descricao' => 'VENDAS ACESSORIOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.017', 'descricao' => 'CONFECCAO', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => 'R']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'01.01.018', 'descricao' => 'VENDAS ACESSÓRIOS DA MODA', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.22.', 'descricao' => 'EMPRESTIMOS', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
        ClassificacaoFinanceiraModel::Create(['codigo' =>'02.22.001', 'descricao' => 'PRONAMPE', 'titulo_grupo' => 'S', 'ativo' => 'S', 'receita_despesa' => '']);
    }
}
